language: java
script: mvn package
jdk:
- oraclejdk8
- oraclejdk7
notifications:
  slack:
    secure: eXnZMpVI7DmlMpnGljnKZqEUlFtZAHSy7mBLwf1jmC79yB9UcSyjHPuJM03onjPizTFxW5AiOwPG4wkvi6d4uagFIoPvmBV681PvJ/eHNRxXF9j+8VcP6GWFuTLzZDp8Vh8tb0Cj7bR/chiVI9LkYX8E59B8pwRj2gX/ueTL5ORf+t/Q6NIYxn28imzk3LS66jzyjH+XwiKcsojJHJgfEv+pQvwf7tC2UuXs+ZYV4C14QA+jeArF33pQjhYxxHIKX4AKQUTJxlYLbhXHZraWuLjuZqU2IispDNhNotN3M5D1RhSUuROYDuk4ewpJotpweS8d8MA0Mp4TaqxVNWu01fuxwOl7qzKBaVsW5j5GNUaRUpwMN8tAYlDEZz0LKesM2Ij0PgEehiNzJVEOKOoxz7twK0ia+dm1cy1iP+mu0D0G5TkCGrSgGLmAMYcqBF2WP6rqbTdWu8QvqPvKj8UjCfRLdA57wXk/QtjB6yPFFBoFlaciBFbMuS/tp6D7VTKvIi448YaVFpkGJb0kF9mMJv/OtImEX0hJOyD0HNE2gCpWQYOZPjtEmMWfQhYCQX7Me6KncfjYQnRbAJFy2wF5/iRmIAmnOuMFy8Ufpwx3vuB4DpJTVt5US8OsMSp0l8MEyLg7cklKlu17HOoiwxCfvv9VeSH8EtCUGeb2VKNayCw=
